//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reciclemos_v2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiales_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materiales_detalle()
        {
            this.solicitud_detalle = new HashSet<solicitud_detalle>();
        }
    
        public int idMatDet { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idMateriales { get; set; }
    
        public virtual materiales materiales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud_detalle> solicitud_detalle { get; set; }
    }
}
